/* eslint-disable import/prefer-default-export */
/* Populated by react-webpack-redux:action */

export const GET_SCRATCH_CARD_REQUEST = 'GET_SCRATCH_CARD_REQUEST';
export const GET_SCRATCH_CARD_SUCCESS = 'GET_SCRATCH_CARD_SUCCESS';
export const GET_SCRATCH_CARD_FAILED = 'GET_SCRATCH_CARD_FAILED';

export const GET_MERCHANT_LIST_REQUEST = 'GET_MERCHANT_LIST_REQUEST';
export const GET_MERCHANT_LIST_SUCCESS = 'GET_MERCHANT_LIST_SUCCESS';
export const GET_MERCHANT_LIST_FAILED = 'GET_MERCHANT_LIST_FAILED';

export const GET_MY_LINK_CARD_REQUEST = 'GET_MY_LINK_CARD_REQUEST';
export const GET_MY_LINK_CARD_SUCCESS = 'GET_MY_LINK_CARD_SUCCESS';
export const GET_MY_LINK_CARD_FAILED = 'GET_MY_LINK_CARD_FAILED';

/**Login Actions */
export const POST_EMAIL_LOGIN_REQUEST = 'POST_EMAIL_LOGIN_REQUEST';
export const POST_EMAIL_LOGIN_SUCCESS = 'POST_EMAIL_LOGIN_SUCCESS';
export const POST_EMAIL_LOGIN_FAILED = 'POST_EMAIL_LOGIN_FAILED'

export const POST_FACEBOOK_LOGIN_REQUEST = 'POST_FACEBOOK_LOGIN_REQUEST';
export const POST_FACEBOOK_LOGIN_SUCCESS = 'POST_FACEBOOK_LOGIN_SUCCESS';
export const POST_FACEBOOK_LOGIN_FAILED = 'POST_FACEBOOK_LOGIN_FAILED';

export const POST_LOGOUT_REQUEST = 'POST_LOGOUT_REQUEST';
export const POST_LOGOUT_SUCCESS = 'POST_LOGOUT_SUCCESS';
export const POST_LOGOUT_FAILED = 'POST_LOGOUT_FAILED';
